### PR TITLE
Fix headers already sent error

### LINKED ISSUE #19: Possible 'Headers already sent' errors
This was spotted when trying to migrate `vip-ui` to the `server` module.

### Current behavior:
Our current matcher for the health check route will respond to the client and pass the request along. If the client is using a general matcher for routes, i.e. `app.get('*')`, this will trigger another HTTP response and cause an `Headers already sent` error

### Desired behavior:
Respond with our matcher only

### Steps to correct the bug:
Make the handler return after responding instead of passing the call

### PR DESCRIPTION
**Pull request by elazzabi**
Fixes #19 

This will return and terminate the request instead of passing it to the next handler

### CODE REVIEW

**Comment by mjangda** [comment]
Is there a test we can add to catch this?

**Comment by elazzabi** [comment]
Hmm I'm not sure what kind of test we can add 🤔when this happens, it only logs to the console and continue... Not sure how can we test this 🤔

**Comment by nickdaugherty** [comment]
This would be a good use of spies / mock functions - since we know `console.log()` is getting called when it shouldn't, we can mock `console.log()` then ensure it was never called when we make a request to it.

https://jestjs.io/docs/en/mock-functions

So something like...

```
const originalLog = console.log;

console.log = jest.fn();

// ... run a test request...hit healthcheck for example

expect( console.log ).not.toHaveBeenCalled();

console.log = originalLog;
```

**Comment by nickdaugherty** [comment]
Better code than what I wrote above would be:

```
const spy = jest.spyOn( console, 'log' );

... run request

expect( console.log ).not.toHaveBeenCalled();

// Restores the original `console.log` function
spy.restoreMock();
```

**Comment by elazzabi** [comment]
Yess, given we're not logging from different middleware... that will work. I'll implement it. Thanks!

**Comment by elazzabi** [comment]
Looks like I can't reproduce it in tests (because we're using a library to mock the server and not actually starting the server?), so I've added a `console.log` to the request handler. I'm not sure if this is clean or are we really testing it using this...

What do you think @nickdaugherty ?

**Pull request merged**
